"""criando tabelas

Revision ID: aa992a6ea611
Revises: 
Create Date: 2025-12-27 08:19:29.419764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa992a6ea611'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=True),
    sa.Column('cnpj_cpf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('endereco_completo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.add_column('transacoes', sa.Column('valor', sa.Float(), nullable=False))
    op.add_column('transacoes', sa.Column('qtd_parcelas', sa.Integer(), nullable=False))
    op.add_column('transacoes', sa.Column('dono_id', sa.Integer(), nullable=False))
    op.alter_column('transacoes', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transacoes', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transacoes', 'instituicao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transacoes', 'forma_pagamento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transacoes', 'tipo_documento',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.create_foreign_key(None, 'transacoes', 'users', ['dono_id'], ['id'])
    op.drop_column('transacoes', 'parcela_atual')
    op.drop_column('transacoes', 'moeda')
    op.drop_column('transacoes', 'valor_total')
    op.drop_column('transacoes', 'total_parcelas')
    op.drop_column('transacoes', 'valor_parcela')
    op.drop_column('transacoes', 'criador_id')
    op.drop_column('transacoes', 'detalhes_fiscais')
    op.drop_column('transacoes', 'data_emissao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('data_emissao', sa.DATETIME(), nullable=True))
    op.add_column('transacoes', sa.Column('detalhes_fiscais', sa.VARCHAR(), nullable=True))
    op.add_column('transacoes', sa.Column('criador_id', sa.INTEGER(), nullable=True))
    op.add_column('transacoes', sa.Column('valor_parcela', sa.FLOAT(), nullable=True))
    op.add_column('transacoes', sa.Column('total_parcelas', sa.INTEGER(), nullable=True))
    op.add_column('transacoes', sa.Column('valor_total', sa.FLOAT(), nullable=True))
    op.add_column('transacoes', sa.Column('moeda', sa.VARCHAR(), nullable=True))
    op.add_column('transacoes', sa.Column('parcela_atual', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.create_foreign_key(None, 'transacoes', 'usuarios', ['criador_id'], ['id'])
    op.alter_column('transacoes', 'tipo_documento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transacoes', 'forma_pagamento',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transacoes', 'instituicao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transacoes', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transacoes', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transacoes', 'dono_id')
    op.drop_column('transacoes', 'qtd_parcelas')
    op.drop_column('transacoes', 'valor')
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('senha', sa.VARCHAR(), nullable=True),
    sa.Column('funcao', sa.VARCHAR(), nullable=True),
    sa.Column('nome_empresa', sa.VARCHAR(), nullable=True),
    sa.Column('cnpj_cpf', sa.VARCHAR(), nullable=True),
    sa.Column('email_contato', sa.VARCHAR(), nullable=True),
    sa.Column('telefone', sa.VARCHAR(), nullable=True),
    sa.Column('endereco_completo', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=1)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
